# PAUdm - Common configuration File (YAML)

general:
    env_mode        :   GRID                       # Environment [PC/GRID]
    archive_path    :   /pnfs/pic.es/data/vo.paus.pic.es/paus/tape/eraseme/preDC4_bt_4/
    working_path    :   $HOME                      # Working path
    project         :   PAU

logging:
    screen_level    :   DEBUG                      # Log level for the screen handler [DEBUG/INFO/WARNING/CRITICAL/ERROR]
    file_level      :   DEBUG                      # Log level for the file handler   [DEBUG/INFO/WARNING/CRITICAL/ERROR]
    sql_level       :   WARNING                    # Base log level for sqlalchemy    [DEBUG/INFO/WARNING/CRITICAL/ERROR]
    path            :   Default                    # Log file path (Default is WORKING_PATH/PAUdm.log )

database:
    create_db       :   False                      # Create new DB or overrite existing one - BE CAREFULL!
    db_name         :   dm                         # Name for the data base (in SQLite has .db extension)
    path            :   /home/paus001/.sqlite/     # Path for the data base (PC Only)

grid:
    archive_type    :   STORAGE                        # Choose where to export the produced simulation [STORAGE; NFS; NONE] 
    NFS_PATH        :   /nfs/pau/PAUdm/runs/tonello/bt_test_nt/shared_1/
    SEXTRACTOR_BIN  :   $VO_VO_PAUS_PIC_ES_SW_DIR/sextractor/r321/bin/sex
    SCAMP_BIN       :   $VO_VO_PAUS_PIC_ES_SW_DIR/scamp/r314/bin/scamp
    ACLIENT_BIN     :   $VO_VO_PAUS_PIC_ES_SW_DIR/cdsclient/3.6/bin/aclient
    MISSFITS_BIN    :   $VO_VO_PAUS_PIC_ES_SW_DIR/missfits/2.4.0/bin/missfits
    SKYMAKER_BIN    :   $VO_VO_PAUS_PIC_ES_SW_DIR/skymaker/3.8.2-flat/bin/sky
    PSFEX_BIN       :   $VO_VO_PAUS_PIC_ES_SW_DIR/psfex/3.15.2/bin/psfex
    FUNPACK_BIN     :   /software/vo.paus.pic.es/funpack/1.6.0/bin/funpack
    FILE_PREFIX     :   file:////                  # File prefix used at SRM copies
    SRM_prefix      :   srm://srm.pic.es:8443/srm/managerv2?SFN=   # SRM prefix
    SRM_COPY_CMD    :   lcg-cp                     # SRM copy command [srmcp/lcg-cp]
    #SPATIALINDEX_LIB:   /software/vo.paus.pic.es/spatialindex/1.6.1-3.el6/lib64/libspatialindex_c.so
